title: "AraGenEval"
#description: "Call for Participation: AraGenEval"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/7oaGv2z4nR6MFHbd7"
  repository_name: "Register Now"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

