title: "AraGenEval"
#description: "Call for Participation: AraGenEval"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://docs.google.com/forms/d/e/1FAIpQLSextZDY7qjGRJSLCBNISPcBNQZwusRWKvyxb9uuBxyJddJfdA/viewform?usp=header"
  repository_name: "Register Now"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

